
project_id = "aqxmhzgnsngxgdfshlkn"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54325
file_size_limit = "50MiB"

[auth]
enabled = true
port = 54326
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://aqxmhzgnsngxgdfshlkn.supabase.co"]
jwt_expiry = 3600
jwt_secret = "super-secret-jwt-token-with-at-least-32-characters-long"
enable_signup = true
email_confirm = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[edge_functions]
enabled = true
port = 54327

[functions.create-payment-link]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.n8n-webhook-handler]
verify_jwt = false

[functions.get-server-date]
verify_jwt = true
