// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzrxhihviacenkgwiier.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6cnhoaWh2aWFjZW5rZ3dpaWVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMTU0NDIsImV4cCI6MjA2NTY5MTQ0Mn0.JOgkcCWvfayfpiRRJj-gPz9OJCS97yofcGJo_LguS-E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);