// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://stydrjtstqlozbonskxo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN0eWRyanRzdHFsb3pib25za3hvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMzA1OTMsImV4cCI6MjA2NzkwNjU5M30.gZfuy-2RelD6QBj0Rh9k991REEm3leNcaGTh6f0z0Y0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);